[features]
seeds = false
skip-lint = false
[programs.localnet]
mad_raffle = "MAD7rNGHFjheUdatt9tfx4Jruz9S9aKq5PVWQbFbLqq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
